# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

jobs:
  run:
#     docker:
#       - image: cimg/base:2021.04
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - run: echo "Hello world"

workflows:
  monitor:
    jobs:
      - run
