# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

jobs:
  RunMachine:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - run: echo "Machine execution run"
  RunDocker:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run: echo "Docker execution run"

workflows:
  monitorMachine:
    jobs:
      - RunMachine
  monitorDocker:
    jobs:
      - RunDocker
