on:
  workflow_dispatch:
    inputs:
      uuid:
        name: 'Unique ID of this run'
        required: true
      webhook_url:
        name: 'Where to send the unique id message to'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Allways all good
        run: echo curl -d '{"uuid":"${{ github.event.inputs.uuid }}"}' ${{ github.event.inputs.webhook_url }}
